server {
    listen 80;
    server_name hookedonbass.co.uk www.hookedonbass.co.uk;

    root /var/www/hooked-on-bass;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|svg|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}